import type { FastifyInstance } from "fastify";
import { z } from "zod";
import type { ActivationCodeService } from "../activation.js";
import { ADMIN_CSRF_COOKIE, ADMIN_CSRF_HEADER, ADMIN_SESSION_COOKIE, adminSessionMaxAgeSeconds, type AdminAuthService } from "../adminAuth.js";
import { renderAdminLoginPage, renderAdminPage } from "../adminPage.js";
import { detectLocale, extractQueryLang } from "../i18n.js";
import type { EntitlementAdjustmentService } from "../entitlementAdjustment.js";
import type { LlmConfigService } from "../llmConfig.js";
import { sha256 } from "../security.js";
import type { AdminSessionRecord, Store } from "../store.js";
import { parseCookies, setCookie } from "./cookies.js";
import { isServerTemporarilyUnavailable, publicAuthError } from "./shared.js";

type Dependencies = { store: Pick<Store, "revokeAdminSession" | "listUsers" | "getEntitlement" | "listActivationCodes" | "listAdminEntitlementAdjustments">; auth: AdminAuthService; activationCodes: ActivationCodeService; llmConfig: LlmConfigService; adjustments: EntitlementAdjustmentService; adminEmail: string; secureCookies?: boolean; now?: () => Date };
const state = z.string().min(8).max(160).regex(/^[A-Za-z0-9._~-]+$/);
const startSchema = z.object({ state }).strict(); const verifySchema = z.object({ state, code: z.string().regex(/^\d{6}$/) }).strict();
const activationSchema = z.object({ redeem_window_days: z.number().int().min(1).max(365).optional() }).strict();
const llmSchema = z.object({ provider: z.enum(["openai", "openai_compatible"]), base_url: z.string().max(2048), model: z.string().min(1).max(256), api_key: z.string().min(8).max(4096), timeout_seconds: z.number().int().min(1).max(600) }).strict();
const adjustmentSchema = z.object({ reason: z.string().min(1).max(160), note: z.string().max(1024).optional(), extend_days: z.number().int().min(1).max(36500).optional(), expires_at: z.string().datetime().optional(), quota_add: z.number().int().min(1).max(1_000_000).optional() }).strict().refine((v) => v.extend_days !== undefined || v.expires_at !== undefined || v.quota_add !== undefined).refine((v) => !(v.extend_days !== undefined && v.expires_at !== undefined));
const userParams = z.object({ userId: z.string().min(1).max(256) }).strict();

export function registerAdminRoutes(app: FastifyInstance, d: Dependencies) { const now = d.now ?? (() => new Date()); const secure = d.secureCookies ?? true;
  app.get("/admin/login", async (request, reply) => {
    const locale = detectLocale({ cookie: request.headers.cookie, queryLang: extractQueryLang(request.query), acceptLanguage: request.headers["accept-language"] as string | undefined });
    pageHeaders(reply); return reply.type("text/html; charset=utf-8").send(renderAdminLoginPage(locale));
  });
  app.post("/admin/auth/email/start", async (request, reply) => { const parsed = startSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "INVALID_REQUEST" }); try { await d.auth.startEmailLogin({ state: parsed.data.state, ip: request.ip }); return { ok: true }; } catch (e) { return authError(reply, e); } });
  app.post("/admin/auth/email/verify", async (request, reply) => { const parsed = verifySchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "INVALID_REQUEST" }); try { const result = await d.auth.verifyEmailCode(parsed.data); setCookie(reply, ADMIN_SESSION_COOKIE, result.sessionToken, { httpOnly: true, maxAgeSeconds: adminSessionMaxAgeSeconds, secure }); setCookie(reply, ADMIN_CSRF_COOKIE, result.csrfToken, { httpOnly: false, maxAgeSeconds: adminSessionMaxAgeSeconds, secure }); return { ok: true, redirect_url: "/admin" }; } catch (e) { return authError(reply, e); } });
  app.post("/admin/auth/logout", async (request, reply) => { const checked = await adminMutation(d, request.headers.cookie, firstHeader(request.headers[ADMIN_CSRF_HEADER])); if ("error" in checked) return adminFailure(reply, checked.error); try { await d.store.revokeAdminSession(sha256(checked.token), now()); clearCookie(reply, ADMIN_SESSION_COOKIE, true, secure); clearCookie(reply, ADMIN_CSRF_COOKIE, false, secure); return { ok: true, redirect_url: "/admin/login" }; } catch { return unavailable(reply); } });
  app.get("/admin", async (request, reply) => { try { const cookies = parseCookies(request.headers.cookie); const session = await d.auth.authenticate(cookies.get(ADMIN_SESSION_COOKIE) ?? null); if (!session) return reply.redirect("/admin/login"); const users = await d.store.listUsers(); const entitlements = new Map(await Promise.all(users.map(async (u) => [u.id, await d.store.getEntitlement(u.id)] as const))); const [llmConfig, activationCodes, entitlementAdjustments] = await Promise.all([d.llmConfig.getAdminView(), d.store.listActivationCodes(), d.store.listAdminEntitlementAdjustments(50)]); pageHeaders(reply); return reply.type("text/html; charset=utf-8").send(renderAdminPage({ adminEmail: session.email, csrfToken: cookies.get(ADMIN_CSRF_COOKIE) ?? "", users, entitlements, llmConfig, activationCodes, entitlementAdjustments })); } catch { return unavailable(reply); } });
  app.post("/admin/api/activation-codes", async (request, reply) => { const checked = await adminMutation(d, request.headers.cookie, firstHeader(request.headers[ADMIN_CSRF_HEADER])); if ("error" in checked) return adminFailure(reply, checked.error); const parsed = activationSchema.safeParse(request.body ?? {}); if (!parsed.success) return reply.code(400).send({ error: "INVALID_REQUEST" }); try { const generated = await d.activationCodes.generateCode({ redeemBy: parsed.data.redeem_window_days ? new Date(now().getTime() + parsed.data.redeem_window_days * 86_400_000) : undefined }); return { code: generated.code, code_prefix: generated.codePrefix, entitlement_days: generated.entitlementDays, redeem_by: generated.redeemBy.toISOString() }; } catch { return unavailable(reply); } });
  app.post("/admin/api/llm-config", async (request, reply) => { const checked = await adminMutation(d, request.headers.cookie, firstHeader(request.headers[ADMIN_CSRF_HEADER])); if ("error" in checked) return adminFailure(reply, checked.error); const parsed = llmSchema.safeParse(request.body); if (!parsed.success) return reply.code(400).send({ error: "INVALID_REQUEST" }); try { const saved = await d.llmConfig.save({ provider: parsed.data.provider, baseUrl: parsed.data.base_url, model: parsed.data.model, apiKey: parsed.data.api_key, timeoutSeconds: parsed.data.timeout_seconds }); return { configured: saved.configured, api_key_last4: saved.apiKeyLast4 }; } catch (error) { return error instanceof Error && error.message === "INVALID_LLM_CONFIG" ? reply.code(400).send({ error: "INVALID_REQUEST" }) : unavailable(reply); } });
  app.post("/admin/api/users/:userId/entitlement-adjustments", async (request, reply) => { const checked = await adminMutation(d, request.headers.cookie, firstHeader(request.headers[ADMIN_CSRF_HEADER])); if ("error" in checked) return adminFailure(reply, checked.error); const params = userParams.safeParse(request.params); const body = adjustmentSchema.safeParse(request.body); if (!params.success || !body.success) return reply.code(400).send({ error: "INVALID_REQUEST" }); try { const result = await d.adjustments.apply({ adminEmail: checked.session.email, userId: params.data.userId, reason: body.data.reason, note: body.data.note, extendDays: body.data.extend_days, expiresAt: body.data.expires_at ? new Date(body.data.expires_at) : undefined, quotaAdd: body.data.quota_add }); if (result.status === "user_not_found") return reply.code(404).send({ error: "USER_NOT_FOUND" }); if (result.status === "expiry_required") return reply.code(400).send({ error: "EXPIRY_REQUIRED" }); if (!("adjustment" in result)) return reply.code(400).send({ error: "INVALID_REQUEST" }); return { adjustment_id: result.adjustment.id, user_id: params.data.userId, entitlement_expires_at: result.entitlement.expiresAt.toISOString(), llm_quota_limit: result.entitlement.llmQuotaLimit, llm_quota_used: result.entitlement.llmQuotaUsed, llm_quota_remaining: Math.max(0, result.entitlement.llmQuotaLimit - result.entitlement.llmQuotaUsed), reason: result.adjustment.reason }; } catch (error) { return error instanceof Error && error.message === "INVALID_ENTITLEMENT_ADJUSTMENT" ? reply.code(400).send({ error: "INVALID_REQUEST" }) : unavailable(reply); } });
}
async function adminMutation(d: Dependencies, cookieHeader: string | undefined, csrfHeader: string | undefined): Promise<{ session: AdminSessionRecord; token: string } | { error: 401 | 403 | 503 }> { try { const cookies = parseCookies(cookieHeader); const token = cookies.get(ADMIN_SESSION_COOKIE); const session = await d.auth.authenticate(token ?? null); if (!token || !session) return { error: 401 }; const cookieCsrf = cookies.get(ADMIN_CSRF_COOKIE); if (!csrfHeader || !cookieCsrf || csrfHeader !== cookieCsrf || !d.auth.validateCsrf(session, csrfHeader)) return { error: 403 }; return { session, token }; } catch { return { error: 503 }; } }
function authError(reply: { code(status: number): { send(value: unknown): unknown } }, error: unknown) { if (isServerTemporarilyUnavailable(error)) return unavailable(reply); const publicMessage = publicAuthError(error); return publicMessage ? reply.code(400).send({ error: publicMessage }) : unavailable(reply); }
function adminFailure(reply: { code(status: number): { send(value: unknown): unknown } }, status: 401 | 403 | 503) { if (status === 401) return reply.code(401).send({ error: "ADMIN_AUTH_REQUIRED" }); if (status === 403) return reply.code(403).send({ error: "CSRF_INVALID" }); return unavailable(reply); }
function unavailable(reply: { code(status: number): { send(value: unknown): unknown } }) { return reply.code(503).send({ error: "SERVER_TEMPORARILY_UNAVAILABLE" }); }
function pageHeaders(reply: { header(name: string, value: string): unknown }) { reply.header("cache-control", "no-store"); reply.header("content-security-policy", "default-src 'self'; script-src 'unsafe-inline'; style-src 'self' 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'"); reply.header("x-content-type-options", "nosniff"); }
function firstHeader(value: string | string[] | undefined) { return Array.isArray(value) ? value[0] : value; }
function clearCookie(reply: Parameters<typeof setCookie>[0], name: string, httpOnly: boolean, secure: boolean) { setCookie(reply, name, "", { httpOnly, maxAgeSeconds: 0, secure }); }
