import type { FastifyInstance } from "fastify";
import { renderDashboardPage, type DashboardAccountView } from "../dashboardPage.js";
import type { LlmConfigService } from "../llmConfig.js";
import type { Store } from "../store.js";
import type { UserAuthService } from "../userAuth.js";
import { parseCookies } from "./cookies.js";
type Dependencies = { store: Pick<Store, "getUserById" | "getEntitlement">; auth: UserAuthService; llmConfig: LlmConfigService; now?: () => Date };
export function registerDashboardRoutes(app: FastifyInstance, d: Dependencies) { const now = d.now ?? (() => new Date());
  app.get("/dashboard", async (request, reply) => { try { const cookies = parseCookies(request.headers.cookie); const session = await d.auth.authenticate(cookies.get("studymind_user_session") ?? null); if (!session) return reply.redirect("/login"); const account = await accountPayload(d, session.userId, now()); reply.header("cache-control", "no-store").header("content-security-policy", "default-src 'self'; script-src 'unsafe-inline'; style-src 'self' 'unsafe-inline'; base-uri 'none'; frame-ancestors 'none'").header("x-content-type-options", "nosniff").type("text/html; charset=utf-8"); return renderDashboardPage({ account, csrfToken: cookies.get("studymind_user_csrf") ?? "" }); } catch { return unavailable(reply); } });
  app.get("/api/dashboard/account", async (request, reply) => { try { const session = await d.auth.authenticate(parseCookies(request.headers.cookie).get("studymind_user_session") ?? null); if (!session) return reply.code(401).send({ error: "AUTH_REQUIRED" }); const account = await accountPayload(d, session.userId, now()); reply.header("cache-control", "no-store"); return account; } catch { return unavailable(reply); } });
}
async function accountPayload(d: Dependencies, userId: string, now: Date): Promise<DashboardAccountView> { const [user, entitlement, configured] = await Promise.all([d.store.getUserById(userId), d.store.getEntitlement(userId), d.llmConfig.isConfigured()]); const active = Boolean(entitlement?.status === "active" && entitlement.expiresAt > now); const limit = entitlement?.llmQuotaLimit ?? 0; const used = entitlement?.llmQuotaUsed ?? 0; const remaining = active ? Math.max(0, limit - used) : 0; return { authenticated: true, email: user?.email ?? "", entitlement_status: active ? "active" : "inactive", entitlement_expires_at: entitlement?.expiresAt.toISOString() ?? null, llm_quota_limit: limit, llm_quota_used: used, llm_quota_remaining: remaining, llm_quota_resets_at: active ? entitlement?.expiresAt.toISOString() ?? null : null, llm_configured: configured, last_verified_at: now.toISOString(), can_process: active, can_generate_ai: active && remaining > 0 && configured }; }
function unavailable(reply: { code(status: number): { send(value: unknown): unknown } }) { return reply.code(503).send({ error: "SERVER_TEMPORARILY_UNAVAILABLE" }); }
