from __future__ import annotations

from collections.abc import Callable

PROGRESS_EVENT_PREFIX = "STUDYMIND_PROGRESS "
MODEL_DOWNLOAD_EVENT_PREFIX = "STUDYMIND_MODEL_DOWNLOAD "
DESKTOP_WORKER_CONTRACT_VERSION = 7
LOCAL_MEDIA_CONTRACT_VERSION = 4
PROCESS_VIDEO_CONTRACT_VERSION = 3

VIDEO_EXTENSIONS = frozenset({"mp4", "m4v", "mov", "mkv", "avi", "wmv", "webm"})
AUDIO_EXTENSIONS = frozenset(
    {"mp3", "wav", "m4a", "aac", "flac", "ogg", "opus", "wma"}
)

OUTPUT_DIR_ENV = "STUDYMIND_OUTPUT_DIR"
CACHE_DIR_ENV = "STUDYMIND_CACHE_DIR"
ASR_MODEL_ENV = "STUDYMIND_ASR_MODEL"
MODEL_DIR_ENV = "STUDYMIND_MODEL_DIR"
MODEL_DOWNLOAD_URL_ENV = "STUDYMIND_ASR_MODEL_DOWNLOAD_URL"
MODEL_DOWNLOAD_SHA256_ENV = "STUDYMIND_ASR_MODEL_DOWNLOAD_SHA256"
MODELSCOPE_ENDPOINT_ENV = "STUDYMIND_MODELSCOPE_ENDPOINT"
SENSEVOICE_REVISION_ENV = "STUDYMIND_SENSEVOICE_REVISION"

ProgressCallback = Callable[[dict[str, object]], None]
