import Fastify from "fastify";
import { describe, expect, test } from "vitest";
import { LlmConfigService } from "../src/llmConfig.js";
import { registerDashboardRoutes } from "../src/routes/dashboard.js";
import { registerUserAuthRoutes } from "../src/routes/userAuth.js";
import { MemoryStore } from "../src/store.js";
import { UserAuthService } from "../src/userAuth.js";

const now = new Date("2026-08-09T08:00:00.000Z"); const hmac = "test-email-otp-hmac-key-with-at-least-32-bytes";
function fixture() { const store = new MemoryStore(); let sentCode = ""; const auth = new UserAuthService({ store, otpHmacKey: hmac, now: () => now, sendOtp: async (_email, value) => { sentCode = value; } }); const llmConfig = new LlmConfigService({ store, encryptionKey: "test-llm-encryption-key-with-at-least-32-bytes", now: () => now }); const app = Fastify(); registerUserAuthRoutes(app, { store, auth, now: () => now, secureCookies: true }); registerDashboardRoutes(app, { store, auth, llmConfig, now: () => now }); return { app, store, auth, llmConfig, sentCode: () => sentCode }; }
async function login(email = "student@example.com") { const f = fixture(); await f.app.inject({ method: "POST", url: "/user/auth/email/start", payload: { email, state: "web-state-1" } }); const response = await f.app.inject({ method: "POST", url: "/user/auth/email/verify", payload: { email, state: "web-state-1", code: f.sentCode() } }); const headers = Array.isArray(response.headers["set-cookie"]) ? response.headers["set-cookie"] : [String(response.headers["set-cookie"] ?? "")]; const sessionHeader = headers.find((v) => v.startsWith("studymind_user_session="))!; const csrfHeader = headers.find((v) => v.startsWith("studymind_user_csrf="))!; return { ...f, response, sessionHeader, csrfHeader, session: sessionHeader.split(";")[0]!.split("=")[1]!, csrf: csrfHeader.split(";")[0]!.split("=")[1]! }; }

describe("StudyMind web account routes", () => {
  test("starts and verifies email OTP with 90-day secure web cookies", async () => { const { response, sessionHeader, csrfHeader } = await login(); expect(response.json()).toEqual({ ok: true, redirect_url: "/dashboard" }); expect(sessionHeader).toContain("HttpOnly"); expect(sessionHeader).toContain("Secure"); expect(sessionHeader).toContain("Max-Age=7776000"); expect(csrfHeader).not.toContain("HttpOnly"); });
  test("redirects unauthenticated dashboard and rejects unauthenticated account JSON", async () => { const { app } = fixture(); const page = await app.inject({ method: "GET", url: "/dashboard" }); expect(page.statusCode).toBe(302); expect(page.headers.location).toBe("/login"); expect((await app.inject({ method: "GET", url: "/api/dashboard/account" })).statusCode).toBe(401); });
  test("renders escaped dashboard HTML with security headers", async () => { const { app, session } = await login("student+<script>@example.com"); const page = await app.inject({ method: "GET", url: "/dashboard", headers: { cookie: `studymind_user_session=${session}` } }); expect(page.statusCode).toBe(200); expect(page.headers["content-security-policy"]).toBeTruthy(); expect(page.headers["cache-control"]).toBe("no-store"); expect(page.body).toContain("StudyMind"); expect(page.body).not.toContain("<script>@example.com"); expect(page.body).not.toContain(["Frame", "Q"].join("")); expect(page.body).not.toContain(session); });
  test("returns the same processing and AI gates as desktop account logic", async () => { const { app, session } = await login(); const account = await app.inject({ method: "GET", url: "/api/dashboard/account", headers: { cookie: `studymind_user_session=${session}` } }); expect(account.json()).toMatchObject({ authenticated: true, entitlement_status: "inactive", llm_quota_limit: 0, can_process: false, can_generate_ai: false }); });
  test("logout requires matching csrf cookie/header, revokes session, and clears cookies", async () => { const { app, store, session, csrf } = await login(); const cookie = `studymind_user_session=${session}; studymind_user_csrf=${csrf}`; expect((await app.inject({ method: "POST", url: "/user/auth/logout", headers: { cookie } })).statusCode).toBe(403); expect((await app.inject({ method: "POST", url: "/user/auth/logout", headers: { cookie, "x-studymind-csrf": `${csrf}x` } })).statusCode).toBe(403); const response = await app.inject({ method: "POST", url: "/user/auth/logout", headers: { cookie, "x-studymind-csrf": csrf } }); expect(response.json()).toEqual({ ok: true, redirect_url: "/login" }); expect(String(response.headers["set-cookie"])).toContain("Max-Age=0"); expect(store.userSessions[0]?.revokedAt).toEqual(now); expect((await app.inject({ method: "GET", url: "/api/dashboard/account", headers: { cookie: `studymind_user_session=${session}` } })).statusCode).toBe(401); });
  test("maps dashboard page and account dependency failures to a fixed private 503", async () => { const detail = "private database detail"; for (const url of ["/dashboard", "/api/dashboard/account"]) { const f = await login(); f.store.getUserById = async () => { throw new Error(detail); }; const response = await f.app.inject({ method: "GET", url, headers: { cookie: `studymind_user_session=${f.session}` } }); await expectPrivate503(response, detail); } });
  test("maps user start, verify, and logout dependency failures to a fixed private 503", async () => { const detail = "private database detail"; const start = fixture(); start.auth.startEmailLogin = async () => { throw new Error(detail); }; await expectPrivate503(await start.app.inject({ method: "POST", url: "/user/auth/email/start", payload: { email: "user@example.com", state: "web-state-1" } }), detail); const verify = fixture(); verify.auth.verifyEmailCode = async () => { throw new Error(detail); }; await expectPrivate503(await verify.app.inject({ method: "POST", url: "/user/auth/email/verify", payload: { email: "user@example.com", state: "web-state-1", code: "123456" } }), detail); const logout = await login(); logout.auth.authenticate = async () => { throw new Error(detail); }; await expectPrivate503(await logout.app.inject({ method: "POST", url: "/user/auth/logout", headers: { cookie: `studymind_user_session=${logout.session}; studymind_user_csrf=${logout.csrf}`, "x-studymind-csrf": logout.csrf } }), detail); });
});

async function expectPrivate503(response: { statusCode: number; json(): unknown; body: string }, detail: string) { expect(response.statusCode).toBe(503); expect(response.json()).toEqual({ error: "SERVER_TEMPORARILY_UNAVAILABLE" }); expect(response.body).not.toContain(detail); }
