import { createCipheriv, generateKeyPairSync, sign, verify } from "node:crypto";
import { describe, expect, test } from "vitest";
import { monthlyPassPlan } from "../src/billing.js";
import { createWechatNativePayment, createWechatNotificationParser, validateWechatConfig, WechatConfigError, WechatProviderUnavailableError, type WechatConfig } from "../src/wechat.js";

const now = new Date("2026-08-09T08:00:00.000Z");
const merchant = generateKeyPairSync("rsa", { modulusLength: 2048 });
const platform = generateKeyPairSync("rsa", { modulusLength: 2048 });
const apiV3Key = "12345678901234567890123456789012";
const maxProviderResponseBytes = 1024 * 1024;
function secureConfig(overrides: Partial<WechatConfig> = {}): WechatConfig { return { appId: "wx-app", mchId: "merchant", serialNo: "merchant-serial", privateKey: merchant.privateKey.export({ type: "pkcs8", format: "pem" }).toString(), notifyUrl: "https://studymind.example/api/wechat/notify", apiV3Key, platformPublicKey: platform.publicKey.export({ type: "spki", format: "pem" }).toString(), platformSerialNo: "platform-serial", allowInsecureNotify: false, environment: "production", requestTimeoutMs: 10_000, ...overrides }; }
function insecureConfig(overrides: Partial<WechatConfig> = {}): WechatConfig { return { ...secureConfig(), privateKey: "", apiV3Key: "", platformPublicKey: "", platformSerialNo: "", allowInsecureNotify: true, environment: "test", ...overrides }; }
function encryptedResource(value: unknown) { const nonce = Buffer.from("123456789012"); const aad = "resource-aad"; const cipher = createCipheriv("aes-256-gcm", Buffer.from(apiV3Key), nonce); cipher.setAAD(Buffer.from(aad)); const ciphertext = Buffer.concat([cipher.update(JSON.stringify(value)), cipher.final(), cipher.getAuthTag()]); return { algorithm: "AEAD_AES_256_GCM", ciphertext: ciphertext.toString("base64"), nonce: nonce.toString(), associated_data: aad }; }
function signedNotification(resource: Record<string, unknown>) { const body = { id: "evt-1", resource: encryptedResource(resource) }; const rawBody = Buffer.from(JSON.stringify(body)); const timestamp = "1786262400"; const nonce = "notify-nonce"; const signature = sign("RSA-SHA256", Buffer.from(`${timestamp}\n${nonce}\n${rawBody.toString()}\n`), platform.privateKey).toString("base64"); return { rawBody, headers: { "wechatpay-timestamp": timestamp, "wechatpay-nonce": nonce, "wechatpay-signature": signature, "wechatpay-serial": "platform-serial" } }; }
function signedProviderHeaders(raw: string, contentLength?: number): Headers { const timestamp = "1786262400"; const nonce = "response-nonce"; const signature = sign("RSA-SHA256", Buffer.from(`${timestamp}\n${nonce}\n${raw}\n`), platform.privateKey).toString("base64"); const headers = new Headers({ "wechatpay-timestamp": timestamp, "wechatpay-nonce": nonce, "wechatpay-signature": signature, "wechatpay-serial": "platform-serial" }); if (contentLength !== undefined) headers.set("content-length", String(contentLength)); return headers; }
const paidResource = { appid: "wx-app", mchid: "merchant", out_trade_no: "sm_order1", transaction_id: "tx-1", trade_state: "SUCCESS", success_time: now.toISOString(), amount: { total: monthlyPassPlan.amountFen, currency: monthlyPassPlan.currency } };

describe("WeChat notification security", () => {
  test("verifies and parses only the signed raw bytes", async () => { const signed = signedNotification(paidResource); const parse = createWechatNotificationParser(secureConfig(), () => now); const parsed = await parse(signed); expect(parsed).toMatchObject({ webhookId: "evt-1", outTradeNo: "sm_order1", transactionId: "tx-1", amountFen: monthlyPassPlan.amountFen, currency: "CNY" }); });
  test("rejects raw-byte tampering and stale signatures", async () => { const signed = signedNotification(paidResource); const parse = createWechatNotificationParser(secureConfig(), () => now); await expect(parse({ ...signed, rawBody: Buffer.from(`${signed.rawBody.toString()} `) })).rejects.toThrow("INVALID_WECHAT_NOTIFICATION"); const timestamp = String(Number(signed.headers["wechatpay-timestamp"]) - 301); const signature = sign("RSA-SHA256", Buffer.from(`${timestamp}\n${signed.headers["wechatpay-nonce"]}\n${signed.rawBody.toString()}\n`), platform.privateKey).toString("base64"); await expect(parse({ rawBody: signed.rawBody, headers: { ...signed.headers, "wechatpay-timestamp": timestamp, "wechatpay-signature": signature } })).rejects.toThrow("INVALID_WECHAT_NOTIFICATION"); });
  test("strictly rejects invalid UTF-8 and invalid JSON raw bodies", async () => { const parse = createWechatNotificationParser(insecureConfig()); await expect(parse({ headers: {}, rawBody: Buffer.from([0xff, 0xfe]) })).rejects.toThrow("INVALID_WECHAT_NOTIFICATION"); await expect(parse({ headers: {}, rawBody: Buffer.from("{broken") })).rejects.toThrow("INVALID_WECHAT_NOTIFICATION"); });
  test("insecure parsing is explicit nonproduction and still reads only raw JSON", async () => { const raw = Buffer.from(JSON.stringify({ id: "dev-event", ...paidResource, out_trade_no: "sm_dev123" })); const parsed = await createWechatNotificationParser(insecureConfig())({ headers: {}, rawBody: raw }); expect(parsed.outTradeNo).toBe("sm_dev123"); expect(() => createWechatNotificationParser(insecureConfig({ environment: "production" }))).toThrow(WechatConfigError); });
  test("rejects successful-looking raw transactions with mismatched payment invariants", async () => { const parse = createWechatNotificationParser(insecureConfig()); for (const value of [{ ...paidResource, appid: "other" }, { ...paidResource, mchid: "other" }, { ...paidResource, trade_state: "NOTPAY" }, { ...paidResource, amount: { total: monthlyPassPlan.amountFen + 1, currency: "CNY" } }, { ...paidResource, amount: { total: monthlyPassPlan.amountFen, currency: "USD" } }]) await expect(parse({ headers: {}, rawBody: Buffer.from(JSON.stringify({ id: "dev-event", ...value })) })).rejects.toThrow("INVALID_WECHAT_NOTIFICATION"); });
});

describe("WeChat configuration and provider boundary", () => {
  test("fails fast with a typed secret-free config error", () => { const secret = "private-invalid-key-material"; for (const overrides of [{ appId: "" }, { mchId: "bad value" }, { serialNo: "" }, { notifyUrl: "http://studymind.example/notify" }, { notifyUrl: "https://user:pass@studymind.example/notify" }, { notifyUrl: "https://studymind.example/notify?q=1" }, { apiV3Key: "too-short" }, { privateKey: secret }, { platformPublicKey: "invalid-platform-key" }, { requestTimeoutMs: 30_001 }, { environment: "staging" as WechatConfig["environment"] }]) { try { validateWechatConfig(secureConfig(overrides)); throw new Error("expected invalid config"); } catch (error) { expect(error).toBeInstanceOf(WechatConfigError); expect(error).toMatchObject({ name: "WechatConfigError", message: "WeChat configuration is invalid." }); expect(Object.prototype.hasOwnProperty.call(error, "cause")).toBe(false); expect(JSON.stringify(error)).not.toContain(secret); } } });
  test("signs the canonical native request and verifies the platform response", async () => { const fetchMock: typeof fetch = async (url, init) => { expect(String(url)).toBe("https://api.mch.weixin.qq.com/v3/pay/transactions/native"); const body = String(init?.body); expect(JSON.parse(body)).toMatchObject({ description: monthlyPassPlan.description, amount: { total: monthlyPassPlan.amountFen, currency: monthlyPassPlan.currency } }); const authorization = String((init?.headers as Record<string, string>).authorization); const fields = Object.fromEntries([...authorization.matchAll(/(mchid|nonce_str|signature|timestamp|serial_no)="([^"]+)"/g)].map((match) => [match[1]!, match[2]!])); const canonical = `POST\n/v3/pay/transactions/native\n${fields.timestamp}\n${fields.nonce_str}\n${body}\n`; expect(verify("RSA-SHA256", Buffer.from(canonical), merchant.publicKey, Buffer.from(fields.signature!, "base64"))).toBe(true); expect(verify("RSA-SHA256", Buffer.from(`${canonical}tampered`), merchant.publicKey, Buffer.from(fields.signature!, "base64"))).toBe(false); const raw = JSON.stringify({ code_url: "weixin://native" }); const timestamp = "1786262400"; const nonce = "response-nonce"; const signature = sign("RSA-SHA256", Buffer.from(`${timestamp}\n${nonce}\n${raw}\n`), platform.privateKey).toString("base64"); return new Response(raw, { status: 200, headers: { "wechatpay-timestamp": timestamp, "wechatpay-nonce": nonce, "wechatpay-signature": signature, "wechatpay-serial": "platform-serial" } }); }; await expect(createWechatNativePayment(secureConfig(), fetchMock, () => now, () => Buffer.alloc(16, 1))({ outTradeNo: "sm_native1", amountFen: monthlyPassPlan.amountFen, description: monthlyPassPlan.description })).resolves.toMatchObject({ codeUrl: "weixin://native" }); });
  test("aborts pending provider calls and returns a typed error without raw cause", async () => { let observedSignal: AbortSignal | null = null; const pending: typeof fetch = async (_url, init) => { const signal = init?.signal ?? null; observedSignal = signal; return await new Promise<Response>((_resolve, reject) => signal!.addEventListener("abort", () => reject(new Error("private timeout detail")), { once: true })); }; const pay = createWechatNativePayment(secureConfig({ requestTimeoutMs: 100 }), pending, () => now); const error = await pay({ outTradeNo: "sm_timeout1", amountFen: monthlyPassPlan.amountFen, description: monthlyPassPlan.description }).catch((value: unknown) => value); expect((observedSignal as AbortSignal | null)?.aborted).toBe(true); expect(error).toBeInstanceOf(WechatProviderUnavailableError); expect(error).toMatchObject({ name: "WechatProviderUnavailableError", message: "WeChat provider is unavailable." }); expect(Object.prototype.hasOwnProperty.call(error, "cause")).toBe(false); expect(JSON.stringify(error)).not.toContain("private timeout detail"); });
  test("cancels and aborts an unknown-length stream immediately when chunks cross one MiB", async () => { let pulls = 0; let cancels = 0; let signal: AbortSignal | null = null; const chunks = [new Uint8Array(600_000), new Uint8Array(600_000), new Uint8Array(1)]; const stream = new ReadableStream<Uint8Array>({ pull(controller) { controller.enqueue(chunks[pulls++]!); }, cancel() { cancels += 1; } }, { highWaterMark: 0 }); const fetchMock: typeof fetch = async (_url, init) => { signal = init?.signal ?? null; return new Response(stream); }; await expect(createWechatNativePayment(secureConfig(), fetchMock, () => now)({ outTradeNo: "sm_stream1", amountFen: monthlyPassPlan.amountFen, description: monthlyPassPlan.description })).rejects.toBeInstanceOf(WechatProviderUnavailableError); expect(pulls).toBe(2); expect(cancels).toBe(1); expect((signal as AbortSignal | null)?.aborted).toBe(true); expect(stream.locked).toBe(false); });
  test("cancels an oversized declared response before reading any chunk", async () => { let pulls = 0; let cancels = 0; let signal: AbortSignal | null = null; const stream = new ReadableStream<Uint8Array>({ pull(controller) { pulls += 1; controller.enqueue(new Uint8Array(1)); }, cancel() { cancels += 1; } }, { highWaterMark: 0 }); const fetchMock: typeof fetch = async (_url, init) => { signal = init?.signal ?? null; return new Response(stream, { headers: { "content-length": String(maxProviderResponseBytes + 1) } }); }; await expect(createWechatNativePayment(secureConfig(), fetchMock, () => now)({ outTradeNo: "sm_header1", amountFen: monthlyPassPlan.amountFen, description: monthlyPassPlan.description })).rejects.toBeInstanceOf(WechatProviderUnavailableError); expect(pulls).toBe(0); expect(cancels).toBe(1); expect((signal as AbortSignal | null)?.aborted).toBe(true); expect(stream.locked).toBe(false); });
  test("accepts an exact-limit signed stream without cancelling it", async () => { const prefix = '{"code_url":"weixin://native","padding":"'; const suffix = '"}'; const raw = prefix + "x".repeat(maxProviderResponseBytes - Buffer.byteLength(prefix + suffix)) + suffix; expect(Buffer.byteLength(raw)).toBe(maxProviderResponseBytes); let offset = 0; let cancels = 0; const bytes = Buffer.from(raw); const stream = new ReadableStream<Uint8Array>({ pull(controller) { if (offset === bytes.length) { controller.close(); return; } const end = Math.min(offset + 131_072, bytes.length); controller.enqueue(bytes.subarray(offset, end)); offset = end; }, cancel() { cancels += 1; } }, { highWaterMark: 0 }); const fetchMock: typeof fetch = async () => new Response(stream, { headers: signedProviderHeaders(raw, maxProviderResponseBytes) }); await expect(createWechatNativePayment(secureConfig(), fetchMock, () => now)({ outTradeNo: "sm_exact01", amountFen: monthlyPassPlan.amountFen, description: monthlyPassPlan.description })).resolves.toMatchObject({ codeUrl: "weixin://native" }); expect(cancels).toBe(0); expect(stream.locked).toBe(false); });
  test("times out a pending stream read, cancels it, and releases the reader lock", async () => { let pulls = 0; let cancels = 0; let signal: AbortSignal | null = null; const stream = new ReadableStream<Uint8Array>({ pull() { pulls += 1; }, cancel() { cancels += 1; } }, { highWaterMark: 0 }); const fetchMock: typeof fetch = async (_url, init) => { signal = init?.signal ?? null; return new Response(stream); }; const pay = createWechatNativePayment(secureConfig({ requestTimeoutMs: 100 }), fetchMock, () => now); await expect(pay({ outTradeNo: "sm_bodytime", amountFen: monthlyPassPlan.amountFen, description: monthlyPassPlan.description })).rejects.toBeInstanceOf(WechatProviderUnavailableError); expect(pulls).toBe(1); expect(cancels).toBe(1); expect((signal as AbortSignal | null)?.aborted).toBe(true); expect(stream.locked).toBe(false); }, 1_000);
});
